//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanVien
{
    public partial class DanhSachPhongBan
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Panel pnlFormPB;
        protected global::System.Web.UI.WebControls.Label lblFormTitlePB;
        protected global::System.Web.UI.WebControls.HiddenField hdfMaPB;
        protected global::System.Web.UI.WebControls.TextBox txtTenPB;
        protected global::System.Web.UI.WebControls.TextBox txtMoTaPB;
        protected global::System.Web.UI.WebControls.Button btnLuuPB;
        protected global::System.Web.UI.WebControls.Button btnHuyPB;
        protected global::System.Web.UI.WebControls.Button btnShowAddPB;
        protected global::System.Web.UI.WebControls.GridView gvPhongBan;

        protected global::System.Web.UI.WebControls.Panel pnlFormCV;
        protected global::System.Web.UI.WebControls.Label lblFormTitleCV;
        protected global::System.Web.UI.WebControls.HiddenField hdfMaCV;
        protected global::System.Web.UI.WebControls.TextBox txtTenCV;
        protected global::System.Web.UI.WebControls.TextBox txtHeSoLuong;
        protected global::System.Web.UI.WebControls.Button btnLuuCV;
        protected global::System.Web.UI.WebControls.Button btnHuyCV;
        protected global::System.Web.UI.WebControls.Button btnShowAddCV;
        protected global::System.Web.UI.WebControls.GridView gvChucVu;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton btnSearch;
    }
}
